### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by edwardando** [EPFL-Center-for-Imaging/splinebox#7]
The `nKnots x nSamples` matrix in eval() is not memory efficient.
For Eddy's laptop which represents an almost perfect image processing machine the cursor between memory or cpu-limiting is too far into the memory-limited...

For reference in 64-bit floats we're hitting 64 GB of ram between 10e8 and 10e9 elements,
Speed doesn't seem to dramatically depend on `nKnots` or `nSamples` being bigger

**Comment by faymanns** [comment]
I have implemented several version of `spline.eval` in a separate [branch](https://github.com/EPFL-Center-for-Imaging/splinebox/blob/eval_performance) and tested their performance [here](https://github.com/EPFL-Center-for-Imaging/splinebox/blob/eval_performance/examples/performance_tests.py). The [results](https://github.com/EPFL-Center-for-Imaging/splinebox/files/14837108/performance_run1_thumper.pdf) show that the memory limited implementation mentioned above, called 'vectorize basis function eval only' in the plot, consistently outperforms the other implementations except for 100+ knots with more than 10,000 sample points.
Since we expect that most applications will use fewer than 100 knots, we will keep this implementation for now.

If you have an application that requires a large number of knots, leave a comment and we might revisit this issue.

*N.B.* There is a work around if you run out of memory. Instead of calling `spline.eval(t)` you can call `np.concatenate([spline.eval(t[:n]), spline.eval(t[n:])])`.
